### ISSUE TITLE
factory example not work on lilygo t-display-s3

### ISSUE THREAD

**Issue by taoloo897** [Xinyuan-LilyGO/T-HMI#15]
I bought this item from aliexpress and it arrive with and example loaded on it and it works ok with next button witch changes the pages.

https://www.aliexpress.com/item/1005005719816754.html?spm=a2g0o.order_list.order_list_main.49.322f1802oPFKyW

After other loaded schetches i loaded from t-hmi library the factory example. it remain in first page with FC CE image shows, the button not works and it remain in this status on serial monitor:

19:39:02.970 -> Turn on the main power
19:39:02.970 -> Power on peripherals, such as the LCD backlight
19:39:02.970 -> Initialize the power button
19:39:02.970 -> Initialize Intel 8080 bus
19:39:02.970 -> Install LCD driver of st7789
19:39:02.970 -> Initialize LCD driver of st7789
19:39:03.102 -> Turn on the LCD backlight
19:39:06.081 -> Initialize touch screen calibration data
19:39:06.081 -> point_1:
19:39:06.081 ->   raw_x: 411  raw_y: 1246
19:39:06.081 -> point_2:
19:39:06.081 ->   raw_x: 284  raw_y: 207
19:39:06.081 -> point_3:
19:39:06.081 ->   raw_x: 320  raw_y: 223
19:39:06.081 -> point_4:
19:39:06.081 ->   raw_x: 342  raw_y: 224
19:39:06.081 -> Initialize the touch screen
19:39:06.081 -> Initialize lvgl

Please help me with your adive what it is wrong in sketch. Thanks in advance.

**Comment by teastainGit** [comment]
To test the huge Factory code I had to copy all of the contents of the T-HMI 'lib' directory and copy to my 'libraries' folder and overwrite the existing.  
The device shows FCC, then asks to calibrate the four points of the touch screen.
I press reset and it re-boots as this.
![T-HMI_small](https://github.com/Xinyuan-LilyGO/T-HMI/assets/80008504/c146776a-3c99-4ef7-9de2-0fbd1c3ef3d6)
Hope this is helpful!
-Terry

**Comment by taoloo897** [comment]
very strange , i selected other board type "esp32-S3-box" and it works, before i left what arduino ide detected board "lilygo t-dislpay-s3"

**Comment by teastainGit** [comment]
Oh, the Arduino IDE has a bug that detects a different board, based on registered types, not necessarily the correct board for you! Annoying and confusing.
All LilyGO S3 boards use:
"ESP32S3 Dev Module" as the board type.
Glad you got it working!
https://github.com/Xinyuan-LilyGO/T-HMI  👍 

<img width="675" alt="Screenshot 2023-10-24 at 9 00 43 AM" src="https://github.com/Xinyuan-LilyGO/T-HMI/assets/80008504/1759274e-70f4-4e71-a80e-15576b999848">

**Comment by taoloo897** [comment]
Thanks. Good luck!
