### ISSUE TITLE
Lot of errors compiling tft example

### ISSUE THREAD

**Issue by andreavalle** [Xinyuan-LilyGO/T-HMI#18]
Hi, I'm testing the T-HMI with Arduino IDE 2.2.1 and get a lot of errors when compiling the tft example from T-HMI-master.
I have copied all the folders and file from "lib" to my Arduino libraries folder.
`In file included from /xxx/Arduino/libraries/TFT_eSPI/TFT_eSPI.cpp:20:
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.c: In member function 'uint8_t TFT_eSPI::readByte()':
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.c:96:8: error: 'gpio_get_level' was not declared in this scope
   96 |   b  = gpio_get_level((gpio_num_t)TFT_D0); // Read three times to allow for bus access time
      |        ^~~~~~~~~~~~~~
In file included from /xxx/Arduino/libraries/TFT_eSPI/TFT_eSPI.h:96,
                 from /xxx/Arduino/libraries/TFT_eSPI/TFT_eSPI.cpp:16:
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.c: In member function 'void TFT_eSPI::pushBlock(uint16_t, uint32_t)':
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:356:26: error: 'GPIO' was not declared in this scope
  356 |     #define GPIO_CLR_REG GPIO.out1_w1tc.val
      |                          ^~~~
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:432:31: note: in expansion of macro 'GPIO_CLR_REG'
  432 |       #define tft_Write_16(C) GPIO_CLR_REG = GPIO_OUT_CLR_MASK; GPIO_SET_REG = set_mask((uint8_t) ((C) >> 8)); WR_H; \
      |                               ^~~~~~~~~~~~
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.c:543:5: note: in expansion of macro 'tft_Write_16'
  543 |     tft_Write_16(color);
      |     ^~~~~~~~~~~~
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:356:26: error: 'GPIO' was not declared in this scope
  356 |     #define GPIO_CLR_REG GPIO.out1_w1tc.val
      |                          ^~~~
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:432:31: note: in expansion of macro 'GPIO_CLR_REG'
  432 |       #define tft_Write_16(C) GPIO_CLR_REG = GPIO_OUT_CLR_MASK; GPIO_SET_REG = set_mask((uint8_t) ((C) >> 8)); WR_H; \
      |                               ^~~~~~~~~~~~
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.c:554:23: note: in expansion of macro 'tft_Write_16'
  554 |   else while (len--) {tft_Write_16(color);}
      |                       ^~~~~~~~~~~~
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.c: In member function 'void TFT_eSPI::pushSwapBytePixels(const void*, uint32_t)':
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:356:26: error: 'GPIO' was not declared in this scope
  356 |     #define GPIO_CLR_REG GPIO.out1_w1tc.val
      |                          ^~~~
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:432:31: note: in expansion of macro 'GPIO_CLR_REG'
  432 |       #define tft_Write_16(C) GPIO_CLR_REG = GPIO_OUT_CLR_MASK; GPIO_SET_REG = set_mask((uint8_t) ((C) >> 8)); WR_H; \
      |                               ^~~~~~~~~~~~
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.c:564:20: note: in expansion of macro 'tft_Write_16'
  564 |   while ( len-- ) {tft_Write_16(*data); data++;}
      |                    ^~~~~~~~~~~~
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.c: In member function 'void TFT_eSPI::pushPixels(const void*, uint32_t)':
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:356:26: error: 'GPIO' was not declared in this scope
  356 |     #define GPIO_CLR_REG GPIO.out1_w1tc.val
      |                          ^~~~
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:432:31: note: in expansion of macro 'GPIO_CLR_REG'
  432 |       #define tft_Write_16(C) GPIO_CLR_REG = GPIO_OUT_CLR_MASK; GPIO_SET_REG = set_mask((uint8_t) ((C) >> 8)); WR_H; \
      |                               ^~~~~~~~~~~~
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.c:574:37: note: in expansion of macro 'tft_Write_16'
  574 |   if(_swapBytes) { while ( len-- ) {tft_Write_16(*data); data++; } }
      |                                     ^~~~~~~~~~~~
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:356:26: error: 'GPIO' was not declared in this scope
  356 |     #define GPIO_CLR_REG GPIO.out1_w1tc.val
      |                          ^~~~
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:436:32: note: in expansion of macro 'GPIO_CLR_REG'
  436 |       #define tft_Write_16S(C) GPIO_CLR_REG = GPIO_OUT_CLR_MASK; GPIO_SET_REG = set_mask((uint8_t) ((C) >> 0)); WR_H; \
      |                                ^~~~~~~~~~~~
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.c:575:27: note: in expansion of macro 'tft_Write_16S'
  575 |   else { while ( len-- ) {tft_Write_16S(*data); data++;} }
      |                           ^~~~~~~~~~~~~
/xxx/Arduino/libraries/TFT_eSPI/TFT_eSPI.cpp: In member function 'void TFT_eSPI::begin_tft_write()':
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:225:22: error: 'GPIO' was not declared in this scope
  225 |         #define CS_L GPIO.out_w1tc = (1 << TFT_CS)
      |                      ^~~~
/xxx/Arduino/libraries/TFT_eSPI/TFT_eSPI.cpp:80:5: note: in expansion of macro 'CS_L'
   80 |     CS_L;
      |     ^~~~
/xxx/Arduino/libraries/TFT_eSPI/TFT_eSPI.cpp: In member function 'virtual void TFT_eSPI::begin_nin_write()':
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:225:22: error: 'GPIO' was not declared in this scope
  225 |         #define CS_L GPIO.out_w1tc = (1 << TFT_CS)
      |                      ^~~~
/xxx/Arduino/libraries/TFT_eSPI/TFT_eSPI.cpp:92:5: note: in expansion of macro 'CS_L'
   92 |     CS_L;
      |     ^~~~
/xxx/Arduino/libraries/TFT_eSPI/TFT_eSPI.cpp: In member function 'void TFT_eSPI::end_tft_write()':
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:226:22: error: 'GPIO' was not declared in this scope
  226 |         #define CS_H GPIO.out_w1ts = (1 << TFT_CS)
      |                      ^~~~
/xxx/Arduino/libraries/TFT_eSPI/TFT_eSPI.cpp:106:7: note: in expansion of macro 'CS_H'
  106 |       CS_H;
      |       ^~~~
/xxx/Arduino/libraries/TFT_eSPI/TFT_eSPI.cpp: In member function 'virtual void TFT_eSPI::end_nin_write()':
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:226:22: error: 'GPIO' was not declared in this scope
  226 |         #define CS_H GPIO.out_w1ts = (1 << TFT_CS)
      |                      ^~~~
/xxx/Arduino/libraries/TFT_eSPI/TFT_eSPI.cpp:121:7: note: in expansion of macro 'CS_H'
  121 |       CS_H;
      |       ^~~~
/xxx/Arduino/libraries/TFT_eSPI/TFT_eSPI.cpp: In member function 'void TFT_eSPI::begin_tft_read()':
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:225:22: error: 'GPIO' was not declared in this scope
  225 |         #define CS_L GPIO.out_w1tc = (1 << TFT_CS)
      |                      ^~~~
/xxx/Arduino/libraries/TFT_eSPI/TFT_eSPI.cpp:147:4: note: in expansion of macro 'CS_L'
  147 |    CS_L;
      |    ^~~~
/xxx/Arduino/libraries/TFT_eSPI/TFT_eSPI.cpp: In member function 'void TFT_eSPI::end_tft_read()':
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:226:22: error: 'GPIO' was not declared in this scope
  226 |         #define CS_H GPIO.out_w1ts = (1 << TFT_CS)
      |                      ^~~~
/xxx/Arduino/libraries/TFT_eSPI/TFT_eSPI.cpp:169:24: note: in expansion of macro 'CS_H'
  169 |    if(!inTransaction) {CS_H;}
      |                        ^~~~
/xxx/Arduino/libraries/TFT_eSPI/TFT_eSPI.cpp: In member function 'void TFT_eSPI::spiwrite(uint8_t)':
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:356:26: error: 'GPIO' was not declared in this scope
  356 |     #define GPIO_CLR_REG GPIO.out1_w1tc.val
      |                          ^~~~
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:412:27: note: in expansion of macro 'GPIO_CLR_REG'
  412 |   #define tft_Write_8(C)  GPIO_CLR_REG =  GPIO_OUT_CLR_MASK; GPIO_SET_REG = set_mask((uint8_t)(C)); WR_H
      |                           ^~~~~~~~~~~~
/xxx/Arduino/libraries/TFT_eSPI/TFT_eSPI.cpp:970:3: note: in expansion of macro 'tft_Write_8'
  970 |   tft_Write_8(c);
      |   ^~~~~~~~~~~
/xxx/Arduino/libraries/TFT_eSPI/TFT_eSPI.cpp: In member function 'void TFT_eSPI::writecommand(uint8_t)':
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:167:20: error: 'GPIO' was not declared in this scope
  167 |       #define DC_C GPIO.out_w1tc = (1 << TFT_DC)
      |                    ^~~~
/xxx/Arduino/libraries/TFT_eSPI/TFT_eSPI.cpp:984:3: note: in expansion of macro 'DC_C'
  984 |   DC_C;
      |   ^~~~
/xxx/Arduino/libraries/TFT_eSPI/TFT_eSPI.cpp: In member function 'void TFT_eSPI::writedata(uint8_t)':
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:168:20: error: 'GPIO' was not declared in this scope
  168 |       #define DC_D GPIO.out_w1ts = (1 << TFT_DC)
      |                    ^~~~
/xxx/Arduino/libraries/TFT_eSPI/TFT_eSPI.cpp:1047:3: note: in expansion of macro 'DC_D'
 1047 |   DC_D;        // Play safe, but should already be in data mode
      |   ^~~~
/xxx/Arduino/libraries/TFT_eSPI/TFT_eSPI.cpp: In member function 'uint8_t TFT_eSPI::readcommand8(uint8_t, uint8_t)':
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:225:22: error: 'GPIO' was not declared in this scope
  225 |         #define CS_L GPIO.out_w1tc = (1 << TFT_CS)
      |                      ^~~~
/xxx/Arduino/libraries/TFT_eSPI/TFT_eSPI.cpp:1070:3: note: in expansion of macro 'CS_L'
 1070 |   CS_L;
      |   ^~~~
/xxx/Arduino/libraries/TFT_eSPI/TFT_eSPI.cpp: In member function 'virtual uint16_t TFT_eSPI::readPixel(int32_t, int32_t)':
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:225:22: error: 'GPIO' was not declared in this scope
  225 |         #define CS_L GPIO.out_w1tc = (1 << TFT_CS)
      |                      ^~~~
/xxx/Arduino/libraries/TFT_eSPI/TFT_eSPI.cpp:1148:25: note: in expansion of macro 'CS_L'
 1148 |   if (!inTransaction) { CS_L; } // CS_L can be multi-statement
      |                         ^~~~
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:226:22: error: 'GPIO' was not declared in this scope
  226 |         #define CS_H GPIO.out_w1ts = (1 << TFT_CS)
      |                      ^~~~
/xxx/Arduino/libraries/TFT_eSPI/TFT_eSPI.cpp:1180:27: note: in expansion of macro 'CS_H'
 1180 |     if (!inTransaction) { CS_H; } // CS_H can be multi-statement
      |                           ^~~~
/xxx/Arduino/libraries/TFT_eSPI/TFT_eSPI.cpp: In member function 'void TFT_eSPI::readRect(int32_t, int32_t, int32_t, int32_t, uint16_t*)':
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:225:22: error: 'GPIO' was not declared in this scope
  225 |         #define CS_L GPIO.out_w1tc = (1 << TFT_CS)
      |                      ^~~~
/xxx/Arduino/libraries/TFT_eSPI/TFT_eSPI.cpp:1279:3: note: in expansion of macro 'CS_L'
 1279 |   CS_L;
      |   ^~~~
/xxx/Arduino/libraries/TFT_eSPI/TFT_eSPI.cpp: In member function 'virtual void TFT_eSPI::drawChar(int32_t, int32_t, uint16_t, uint32_t, uint32_t, uint8_t)':
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:356:26: error: 'GPIO' was not declared in this scope
  356 |     #define GPIO_CLR_REG GPIO.out1_w1tc.val
      |                          ^~~~
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:432:31: note: in expansion of macro 'GPIO_CLR_REG'
  432 |       #define tft_Write_16(C) GPIO_CLR_REG = GPIO_OUT_CLR_MASK; GPIO_SET_REG = set_mask((uint8_t) ((C) >> 8)); WR_H; \
      |                               ^~~~~~~~~~~~
/xxx/Arduino/libraries/TFT_eSPI/TFT_eSPI.cpp:3216:32: note: in expansion of macro 'tft_Write_16'
 3216 |         if (column[k] & mask) {tft_Write_16(color);}
      |                                ^~~~~~~~~~~~
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:356:26: error: 'GPIO' was not declared in this scope
  356 |     #define GPIO_CLR_REG GPIO.out1_w1tc.val
      |                          ^~~~
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:432:31: note: in expansion of macro 'GPIO_CLR_REG'
  432 |       #define tft_Write_16(C) GPIO_CLR_REG = GPIO_OUT_CLR_MASK; GPIO_SET_REG = set_mask((uint8_t) ((C) >> 8)); WR_H; \
      |                               ^~~~~~~~~~~~
/xxx/Arduino/libraries/TFT_eSPI/TFT_eSPI.cpp:3217:15: note: in expansion of macro 'tft_Write_16'
 3217 |         else {tft_Write_16(bg);}
      |               ^~~~~~~~~~~~
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:356:26: error: 'GPIO' was not declared in this scope
  356 |     #define GPIO_CLR_REG GPIO.out1_w1tc.val
      |                          ^~~~
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:432:31: note: in expansion of macro 'GPIO_CLR_REG'
  432 |       #define tft_Write_16(C) GPIO_CLR_REG = GPIO_OUT_CLR_MASK; GPIO_SET_REG = set_mask((uint8_t) ((C) >> 8)); WR_H; \
      |                               ^~~~~~~~~~~~
/xxx/Arduino/libraries/TFT_eSPI/TFT_eSPI.cpp:3220:7: note: in expansion of macro 'tft_Write_16'
 3220 |       tft_Write_16(bg);
      |       ^~~~~~~~~~~~
/xxx/Arduino/libraries/TFT_eSPI/TFT_eSPI.cpp: In member function 'virtual void TFT_eSPI::setWindow(int32_t, int32_t, int32_t, int32_t)':
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:167:20: error: 'GPIO' was not declared in this scope
  167 |       #define DC_C GPIO.out_w1tc = (1 << TFT_DC)
      |                    ^~~~
/xxx/Arduino/libraries/TFT_eSPI/TFT_eSPI.cpp:3480:5: note: in expansion of macro 'DC_C'
 3480 |     DC_C; tft_Write_8(TFT_CASET);
      |     ^~~~
/xxx/Arduino/libraries/TFT_eSPI/TFT_eSPI.cpp: In member function 'void TFT_eSPI::readAddrWindow(int32_t, int32_t, int32_t, int32_t)':
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:167:20: error: 'GPIO' was not declared in this scope
  167 |       #define DC_C GPIO.out_w1tc = (1 << TFT_DC)
      |                    ^~~~
/xxx/Arduino/libraries/TFT_eSPI/TFT_eSPI.cpp:3556:3: note: in expansion of macro 'DC_C'
 3556 |   DC_C; tft_Write_8(TFT_CASET);
      |   ^~~~
/xxx/Arduino/libraries/TFT_eSPI/TFT_eSPI.cpp: In member function 'virtual void TFT_eSPI::drawPixel(int32_t, int32_t, uint32_t)':
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:167:20: error: 'GPIO' was not declared in this scope
  167 |       #define DC_C GPIO.out_w1tc = (1 << TFT_DC)
      |                    ^~~~
/xxx/Arduino/libraries/TFT_eSPI/TFT_eSPI.cpp:3756:7: note: in expansion of macro 'DC_C'
 3756 |       DC_C; tft_Write_8(TFT_CASET);
      |       ^~~~
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:167:20: error: 'GPIO' was not declared in this scope
  167 |       #define DC_C GPIO.out_w1tc = (1 << TFT_DC)
      |                    ^~~~
/xxx/Arduino/libraries/TFT_eSPI/TFT_eSPI.cpp:3763:7: note: in expansion of macro 'DC_C'
 3763 |       DC_C; tft_Write_8(TFT_PASET);
      |       ^~~~
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:167:20: error: 'GPIO' was not declared in this scope
  167 |       #define DC_C GPIO.out_w1tc = (1 << TFT_DC)
      |                    ^~~~
/xxx/Arduino/libraries/TFT_eSPI/TFT_eSPI.cpp:3769:3: note: in expansion of macro 'DC_C'
 3769 |   DC_C; tft_Write_8(TFT_RAMWR);
      |   ^~~~
/xxx/Arduino/libraries/TFT_eSPI/TFT_eSPI.cpp: In member function 'virtual void TFT_eSPI::pushColor(uint16_t)':
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:356:26: error: 'GPIO' was not declared in this scope
  356 |     #define GPIO_CLR_REG GPIO.out1_w1tc.val
      |                          ^~~~
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:432:31: note: in expansion of macro 'GPIO_CLR_REG'
  432 |       #define tft_Write_16(C) GPIO_CLR_REG = GPIO_OUT_CLR_MASK; GPIO_SET_REG = set_mask((uint8_t) ((C) >> 8)); WR_H; \
      |                               ^~~~~~~~~~~~
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:596:25: note: in expansion of macro 'tft_Write_16'
  596 |   #define tft_Write_16N tft_Write_16
      |                         ^~~~~~~~~~~~
/xxx/Arduino/libraries/TFT_eSPI/TFT_eSPI.cpp:3790:3: note: in expansion of macro 'tft_Write_16N'
 3790 |   tft_Write_16N(color);
      |   ^~~~~~~~~~~~~
/xxx/Arduino/libraries/TFT_eSPI/TFT_eSPI.cpp: In member function 'virtual int16_t TFT_eSPI::drawChar(uint16_t, int32_t, int32_t, uint8_t)':
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:356:26: error: 'GPIO' was not declared in this scope
  356 |     #define GPIO_CLR_REG GPIO.out1_w1tc.val
      |                          ^~~~
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:432:31: note: in expansion of macro 'GPIO_CLR_REG'
  432 |       #define tft_Write_16(C) GPIO_CLR_REG = GPIO_OUT_CLR_MASK; GPIO_SET_REG = set_mask((uint8_t) ((C) >> 8)); WR_H; \
      |                               ^~~~~~~~~~~~
/xxx/Arduino/libraries/TFT_eSPI/TFT_eSPI.cpp:5317:31: note: in expansion of macro 'tft_Write_16'
 5317 |             if (line & mask) {tft_Write_16(textcolor);}
      |                               ^~~~~~~~~~~~
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:356:26: error: 'GPIO' was not declared in this scope
  356 |     #define GPIO_CLR_REG GPIO.out1_w1tc.val
      |                          ^~~~
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:432:31: note: in expansion of macro 'GPIO_CLR_REG'
  432 |       #define tft_Write_16(C) GPIO_CLR_REG = GPIO_OUT_CLR_MASK; GPIO_SET_REG = set_mask((uint8_t) ((C) >> 8)); WR_H; \
      |                               ^~~~~~~~~~~~
/xxx/Arduino/libraries/TFT_eSPI/TFT_eSPI.cpp:5318:19: note: in expansion of macro 'tft_Write_16'
 5318 |             else {tft_Write_16(textbgcolor);}
      |                   ^~~~~~~~~~~~
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:356:26: error: 'GPIO' was not declared in this scope
  356 |     #define GPIO_CLR_REG GPIO.out1_w1tc.val
      |                          ^~~~
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:432:31: note: in expansion of macro 'GPIO_CLR_REG'
  432 |       #define tft_Write_16(C) GPIO_CLR_REG = GPIO_OUT_CLR_MASK; GPIO_SET_REG = set_mask((uint8_t) ((C) >> 8)); WR_H; \
      |                               ^~~~~~~~~~~~
/xxx/Arduino/libraries/TFT_eSPI/TFT_eSPI.cpp:5323:18: note: in expansion of macro 'tft_Write_16'
 5323 |         if (pX) {tft_Write_16(textbgcolor);}
      |                  ^~~~~~~~~~~~
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:356:26: error: 'GPIO' was not declared in this scope
  356 |     #define GPIO_CLR_REG GPIO.out1_w1tc.val
      |                          ^~~~
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:432:31: note: in expansion of macro 'GPIO_CLR_REG'
  432 |       #define tft_Write_16(C) GPIO_CLR_REG = GPIO_OUT_CLR_MASK; GPIO_SET_REG = set_mask((uint8_t) ((C) >> 8)); WR_H; \
      |                               ^~~~~~~~~~~~
/xxx/Arduino/libraries/TFT_eSPI/TFT_eSPI.cpp:5372:30: note: in expansion of macro 'tft_Write_16'
 5372 |               while (tnp--) {tft_Write_16(textcolor);}
      |                              ^~~~~~~~~~~~
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:356:26: error: 'GPIO' was not declared in this scope
  356 |     #define GPIO_CLR_REG GPIO.out1_w1tc.val
      |                          ^~~~
/xxx/Arduino/libraries/TFT_eSPI/Processors/TFT_eSPI_ESP32_S3.h:432:31: note: in expansion of macro 'GPIO_CLR_REG'
  432 |       #define tft_Write_16(C) GPIO_CLR_REG = GPIO_OUT_CLR_MASK; GPIO_SET_REG = set_mask((uint8_t) ((C) >> 8)); WR_H; \
      |                               ^~~~~~~~~~~~
/xxx/Arduino/libraries/TFT_eSPI/TFT_eSPI.cpp:5374:19: note: in expansion of macro 'tft_Write_16'
 5374 |             else {tft_Write_16(textcolor);}
      |                   ^~~~~~~~~~~~

exit status 1
Compilation error: exit status 1`

Thanks in advance if someone has an idea of what's going on...
Andrea

**Comment by lewisxhe** [comment]
Reduce the esp32 core version to below 3.0.0

**Comment by andreavalle** [comment]
Cool thanks! Downgraded to ESP32 2.0.14 and it compiles without errors.
