### ISSUE TITLE
Which board?

### ISSUE THREAD

**Issue by 369Martin369** [Xinyuan-LilyGO/T-HMI#2]
For Arduino IDE, which Board should be selected? During sketch upload I get following error:

esptool.py v3.0-dev
Serial port COM17
Connecting...
WARNING: This chip doesn't appear to be a ESP32 (date codes 0x03700000:0x00000000). Probably it is unsupported by this version of esptool.
Chip is ESP32-D0WDQ6 (revision 0)
Features: WiFi, BT, Dual Core, Coding Scheme None
WARNING: Detected crystal freq 0.00MHz is quite different to normalized freq 26MHz. Unsupported crystal in use?
Crystal is 26MHz
MAC: 00:00:00:00:00:00
Uploading stub...
Running stub...

A fatal error occurred: Invalid head of packet (0x47)
Failed uploading: uploading error: exit status 2

**Comment by lbuque** [comment]
@369Martin369 

![image](https://user-images.githubusercontent.com/46518962/223991582-727d4f03-5f2f-4566-a7ba-ebdd3909502c.png)

**Comment by 369Martin369** [comment]
Thanks, it worked.  Preferences need latest boardmanager Link:
https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

**Comment by 369Martin369** [comment]
Thanks, it worked. Preferences need latest boardmanager Link:
https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

**Comment by lewisxhe** [comment]
Okay, please contact the merchant. This may be due to a problem with the early power settings that caused the PA to burn down
The power setting of the SX1280 cannot exceed 2-5dB. See README for details
