### ISSUE TITLE
firmware

### ISSUE THREAD

**Issue by 369Martin369** [Xinyuan-LilyGO/T-HMI#4]
please add firmware.bin in branch, so that we can restore to OEM status. Thanks

**Comment by lbuque** [comment]
@369Martin369 

Here's a firmware compiled via github action that you can verify works.

https://github.com/lbuque/T-HMI/actions/runs/4392760071

![image](https://user-images.githubusercontent.com/46518962/224490567-6b63777b-30a6-43eb-b492-de69f816be23.png)

**Comment by 369Martin369** [comment]
BIN file and flash_download_tool_3.9.3 (which you have in T-Display folder "firmware") worked perfect. Thanks
