### ISSUE TITLE
wrong manual

### ISSUE THREAD

**Issue by 369Martin369** [Xinyuan-LilyGO/T-HMI#5]
in readme you say 4) Copy everything from this repository lib folder....
but you have no "repository lib folder" in you branch ?!.

Now you even removed the links to all the Libs needed (e.g. touch)...

Sorry, please imprvove, as I cannot use is as it is....graphics still not running

**Comment by lewisxhe** [comment]
https://github.com/Xinyuan-LilyGO/T-HMI/treeSorry, I mean all the folders in the lib folder in the warehouse
Emmm. How can I explain this step?/master/lib

**Comment by 369Martin369** [comment]
lol, yes now its clear, because you put the lib folder there :-) Before it was not ....
